#!/usr/bin/python3
#	pypgmopts - getopt generator for C
#	Copyright (C) 2018-2020 Johannes Bauer
#
#	This file is part of pypgmopts.
#
#	pypgmopts is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	pypgmopts is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with pypgmopts; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import os
import datetime
import textwrap
import collections
import importlib.util
import mako.lookup
import argparse
from FriendlyArgumentParser import FriendlyArgumentParser

class CustomWidthFormatterClass(argparse.HelpFormatter):
	_WIDTH = 120

	def __init__(self, prog):
		argparse.HelpFormatter.__init__(self, prog, width = self._WIDTH)

	@classmethod
	def set_width(cls, width):
		cls._WIDTH = width

class CodeGenerator(object):
	_Option = collections.namedtuple("Option", [ "name", "requires_parameter", "opt_short", "opt_long", "opt_text", "positional", "nargs", "default" ])

	def __init__(self, args):
		self._args = args
		CustomWidthFormatterClass.set_width(self._args.terminal_width)
		self._parser = self._load_submodule()
		self._parser.formatter_class = CustomWidthFormatterClass
		self._options = self._parse_parser()

	@property
	def have_flexible_positional_argument(self):
		return any(option.nargs is not None for option in self._options)

	@property
	def min_positional_arguments(self):
		min_pos = 0
		for option in self._options:
			if option.positional:
				if option.nargs is None:
					min_pos += 1
				elif option.nargs == "+":
					min_pos += 1
				elif option.nargs in [ "*", "?" ]:
					pass
				else:
					raise Exception("Unsupported 'nargs' argument \"%s\"." % (option.nargs))
		return min_pos

	@property
	def max_positional_arguments(self):
		max_pos = 0
		for option in self._options:
			if option.positional:
				if option.nargs is None:
					max_pos += 1
				elif option.nargs == "?":
					max_pos += 1
				elif option.nargs in [ "+", "*" ]:
					return None
				else:
					raise Exception("Unsupported 'nargs' argument \"%s\"." % (option.nargs))
		return max_pos

	def _parse_parser(self):
		options = [ ]
		for action in self._parser._actions:
			opt_short = None
			opt_long = None
			positional = False
			nargs = None
			default = action.default
			for option in action.option_strings:
				if option.startswith("--"):
					# Long options
					opt_long = option[2:]
				elif (len(option) == 2) and (option[0] == "-"):
					# Short option
					opt_short = option[1]
				else:
					raise Exception("Unknown option: '%s'." % (option))

			if len(action.option_strings) == 0:
				# Positional argument
				positional = True
				nargs = action.nargs
				opt_long = action.dest

			opt_text = [ ]
			if opt_short is not None:
				opt_text.append("-" + opt_short)
			if opt_long is not None:
				if not positional:
					opt_text.append("--" + opt_long)
				else:
					opt_text.append(opt_long)
			opt_text = " / ".join(opt_text)

			option = self._Option(name = action.dest, requires_parameter = (action.nargs != 0), opt_short = opt_short, opt_long = opt_long, opt_text = opt_text, positional = positional, nargs = nargs, default = default)
			options.append(option)
		return options

	def _load_submodule(self):
		spec = importlib.util.spec_from_file_location("parsermodule", self._args.parser)
		parsermodule = importlib.util.module_from_spec(spec)
		spec.loader.exec_module(parsermodule)
		return parsermodule.parser

	@property
	def short_opts_string(self):
		string = ""
		for opt in self._options:
			if opt.opt_short is not None:
				string += opt.opt_short
				if opt.requires_parameter:
					string += ":"
		return string

	def dump(self):
		print("Positional arguments: %s to %s" % (self.min_positional_arguments, self.max_positional_arguments))
		for option in self._options:
			print(option)

	def run(self):
		lookup = mako.lookup.TemplateLookup([ ".", os.path.dirname(sys.argv[0]) ], strict_undefined = True)
		help_text = self._parser.format_help().rstrip("\r\n").split("\n")
		args = {
			"opts":									self._options,
			"short_opts_string":					self.short_opts_string,
			"help_text":							help_text,
			"min_pos":								self.min_positional_arguments,
			"max_pos":								self.max_positional_arguments,
			"have_flexible_positional_argument":	self.have_flexible_positional_argument,
			"now":									datetime.datetime.now(),
			"name_suffix":							"" if (self._args.name is None) else ("_" + self._args.name),
			"pgmname":								self._parser.prog,
		}

		for file_suffix in [ ".c", ".h" ]:
			template = lookup.get_template("argparse_template" + file_suffix)
			result = template.render(**args)
			filename = "argparse" + args["name_suffix"] + file_suffix
			with open(filename, "w") as f:
				f.write(result)

parser = FriendlyArgumentParser(prog = "getoptgen", description = "getoptgen - Generate getopt-style C code from Python argparse", add_help = False)
parser.add_argument("-w", "--terminal-width", type = int, default = 100, help = "Terminal width in characters. Defaults to %(default)d.")
parser.add_argument("-n", "--name", type = str, help = "Distinguish the generated parser by adding a specific separate name. Can be useful to facilitate multiple parsers in one project.")
parser.add_argument("-v", "--verbose", action = "store_true", help = "Be more verbose.")
parser.add_argument("parser", type = str, help = "Python code which contains the parser definition.")
args = parser.parse_args(sys.argv[1:])

codegen = CodeGenerator(args)
if args.verbose:
	codegen.dump()
codegen.run()
